export const SELECT_CUSTOMERS = 'SELECT_CUSTOMERS';
export const SELECT_CUSTOMERS_SUCCESS = 'SELECT_CUSTOMERS_SUCCESS';
export const SELECT_CUSTOMERS_FAILURE = 'SELECT_CUSTOMERS_FAILURE';

export const EDIT_ITEM_CUSTOMERS = 'EDIT_ITEM_CUSTOMERS';
export const EDIT_ITEM_CUSTOMERS_SUCCESS = 'EDIT_ITEM_CUSTOMERS_SUCCESS';
export const EDIT_ITEM_CUSTOMERS_FAILURE = 'EDIT_ITEM_CUSTOMERS_FAILURE';

export const EDIT_ITEM_CUSTOMERS_TABLE = 'EDIT_ITEM_CUSTOMERS_TABLE';

export const DELETE_ITEM_CUSTOMERS = 'DELETE_ITEM_CUSTOMERS';
export const DELETE_ITEM_CUSTOMERS_SUCCESS = 'DELETE_ITEM_CUSTOMERS_SUCCESS';
export const DELETE_ITEM_CUSTOMERS_FAILURE = 'DELETE_ITEM_CUSTOMERS_FAILURE';

export const GET_ITEM_CUSTOMERS = 'GET_ITEM_CUSTOMERS';
export const GET_ITEM_CUSTOMERS_SUCCESS = 'GET_ITEM_CUSTOMERS_SUCCESS';
export const GET_ITEM_CUSTOMERS_FAILURE = 'GET_ITEM_CUSTOMERS_FAILURE';

export const SET_ITEM_CUSTOMERS = 'SET_ITEM_CUSTOMERS';
export const SET_ITEM_CUSTOMERS_SUCCESS = 'SET_ITEM_CUSTOMERS_SUCCESS';
export const SET_ITEM_CUSTOMERS_FAILURE = 'SET_ITEM_CUSTOMERS_FAILURE';
